T5211 py3 port google chat webhook formatting
thinkst/canarytokens pull request #184
Opened 2023-02-07 20:37 UTC by emmanuel-thinkst

port google chat webhook to python 3

Enable integration with Google Chat by formatting our validation message and alerts in a compatible way for `https://chat.googleapis.com` webhook URLs:
![Screenshot 2023-02-07 at 22 21 49](https://user-images.githubusercontent.com/103185449/217359502-0d34f004-2be4-4917-a110-4cc054bdd7d4.png)

The command shown in the validation error message now also works with Google Chat:
![Screenshot 2023-02-07 at 22 24 14](https://user-images.githubusercontent.com/103185449/217359689-0b2e3c22-9dab-4748-90a6-9d1f1a7b215d.png)

2023-02-09 14:00 UTC, wleightond requested changes

2023-02-10 08:12 UTC, emmanuel-thinkst commented on canarytokens/queries.py
> +        models.GoogleChatPayload,
agreed

2023-02-10 08:14 UTC, emmanuel-thinkst commented on canarytokens/queries.py
>      if slack in url:
cool.

2023-02-10 09:12 UTC, wleightond approved these changes

2023-02-10 09:15 UTC, merged