CSS cloned site token
thinkst/canarytokens pull request #297
Opened 2023-09-12 23:06 UTC by ranok

## Proposed changes

This PR adds a new token type that uses CSS to detect a cloned (phishing) site by using a unique image URL that checks the Referer header in a CloudFront Function and if the Referer doesn't match the expected value, it redirects to the token server for alerting.

## Types of changes

What types of changes does your code introduce to this repository?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes (if applicable)
- [ ] I have run pre-commit (`pre-commit` in the repo)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Linked to the relevant github issue or github discussion

## Further comments

By default, this generates a CSS file for use with Azure AD Company Branding, but the url() can be put into any HTML element with the expected referer field set. microsoftonline.com is the expected Azure referer.

2023-09-15 21:08 UTC, ranok commented
These next commits allow for automatic deployment into a tenant. There's probably some UX love that's needed, and more robust error handling, but it's a good baseline.

2024-01-10 21:00 UTC, ranok commented
At this point, I think there are a few things needed:

- [ ] Make the installer Entra application come from the official Azure tenant, and ensure it's using a verified domain
- [ ] If the one-click installer finds an existing installed CSS, it should error more gracefully to the front-end, and provide the user the ability to download the CSS snippet to manually add and upload
- [ ] If the installer has any other issues, it should send them to the front-end
- [ ] Once installed, the installer should verify installation, and pass that information to the front-end instead of immediately closing the authorization pop-up.

2024-01-16 18:15 UTC, jayjb requested changes

2024-01-16 18:15 UTC, jayjb commented on canarytokens/tokens.py
> +        if r_arg != None:
Can we change this to:
```
if r_arg is not None:
```

2024-01-16 18:15 UTC, jayjb commented on frontend/app.py
> +        if css != None and tenant_id != None:
```
if css is not None and tenant_id is not None:
```

2024-01-16 22:27 UTC, ranok commented
I set up a framework for passing information from the Azure auto-installer to the front-end in 69f707d. Will need styling now that it doesn't immediately close itself.

2024-01-17 04:41 UTC, jayjb commented on aws-css-token-infra/CSSClonedSiteCFFunc/index.js
> +    //console.log(event.request.uri);
Rm comment please

2024-01-17 04:41 UTC, jayjb commented on canarytokens/azure_css.py
> +        return (False, f"Installation failed: Unable to automaticall install the CSS, please manually add the following CSS to your branding:<br /><textarea>{css}</textarea>")
`automatically`

2024-01-30 19:15 UTC, jayjb approved these changes

2024-01-30 19:16 UTC, merged