Add Fake IdP SAML App tokens: Frontend
thinkst/canarytokens pull request #623
Opened 2024-11-22 09:33 UTC by wleightond

## Proposed changes
This PR adds the frontend components for fake IdP SAML2 app tokens. 

These are installed as a SAML app on the user's Identity Provider dashboard. When an attacker clicks on the app a SAML request is sent to the canarytokens server with the user's identity, and an alert is triggered.

Changes:
- Add IdP token creation / management frontend UI

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] Lint and unit tests pass locally with my changes (if applicable)
- [x] I have run pre-commit (`pre-commit` in the repo)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation in [canarytokens-docs PR 57](https://github.com/thinkst/canarytokens-docs/pull/57)

2024-11-22 15:13 UTC, mclmax requested changes

2024-11-22 15:13 UTC, mclmax commented on frontend_vue/src/components/tokens/idp_app/howToUse.ts
> +  'Optionally, upload a realistic icon for the service.',
there are each meant to be unique ideas not paragraphs

2024-11-22 15:13 UTC, mclmax commented on frontend_vue/src/components/tokens/idp_app/CreateAppPreview.vue
> +    label: 'idp_icons/elasticsearch.png'
this icon doesn't git

2024-11-22 15:13 UTC, mclmax commented on frontend_vue/src/components/tokens/idp_app/CreateAppPreview.vue
> +    label: 'idp_icons/ms-teams.png'
this isn't a png and has the grid background included

2024-11-22 15:13 UTC, mclmax commented on frontend_vue/src/components/base/BaseDownloadIconButtom.vue
> +<template>
this needs an animation something similar to the copy button

2024-12-03 12:16 UTC, wleightond commented on frontend_vue/src/main.ts
> -  type IconDefinition,
Not as far as I can see.

2024-12-03 13:35 UTC, wleightond commented on frontend_vue/src/utils/tokenServices.ts
> +    documentationLink: '',
Yes! Thanks :) turns out the one I copied from had it missing too. Added to both.

2024-12-03 14:21 UTC, wleightond commented on frontend_vue/src/components/tokens/idp_app/ActivatedToken.vue
> +  <div v-if="!tokenUrl || !entityId">Error loading</div>
[ditto](https://github.com/thinkst/canarytokens/pull/623#discussion_r1867745913)

2024-12-04 15:26 UTC, vittoriaThinkst commented on frontend_vue/src/components/base/BaseLabelArrow.vue
> +    v-bind="$attrs"
This seems to work fine everywhere, tests are passing too

2024-12-04 16:58 UTC, wleightond commented on frontend_vue/src/components/tokens/idp_app/ActivatedToken.vue
> +  <div v-if="!tokenUrl || !entityId">Error loading</div>
Found a way to remove.

2024-12-04 16:58 UTC, wleightond commented on frontend_vue/src/components/tokens/idp_app/ManageToken.vue
> +  <div v-if="!tokenUrl || !entityId">Error loading</div>
Found a way to remove.

2024-12-05 11:07 UTC, wleightond commented on frontend_vue/src/components/base/BaseCopyButton.vue
> +    class="h-[2rem] w-[2rem] font-semibold text-white rounded-full transition duration-100"
no longer needed since the icon is now selected at generation time and will always be present

2024-12-07 22:12 UTC, merged